GET http://localhost:8000/api/movies/

###
GET http://localhost:3000/api/movies/6283b196cbd0543ab90f813b

###
POST http://localhost:8000/api/movies/
Content-Type: application/json

{
    "title":"Spiderman",
    "year":"2012",
    "runtime":"143 min",
    "genre":"Action, Sci-Fi, Thriller",
    "actors":"Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    "plot":"Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    "poster":"http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg"
}

###
PUT http://localhost:3000/api/movies/6283b196cbd0543ab90f813b
Content-Type: application/json

{
    "title":"The Avengers",
    "year":"2012",
    "runtime":"143 min",
    "genre":"Action, Sci-Fi, Thriller",
    "actors":"Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    "plot":"Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    "poster":"http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg"
}

###
DELETE http://localhost:3000/api/movies/62ab5c740bdff76fb3b566e3



###
POST http://localhost:8000/api/auth/
Content-Type: application/json

{
    "name":"Bang Deen",
    "username":"denikurnia111000",
    "password":"denikurnia11"
}

###
GET http://localhost:8000/api/user/

###
GET http://localhost:8000/api/auth/62b32e2b9c2f148f8b9003f7

###
PUT http://localhost:8000/api/auth/62b2fe16dfafe927f1fbc9a0
Content-Type: application/json

{
    "name":"Bang Deen",
    "username":"denikurnia111000",
    "password":"denikurnia112"
}

###
DELETE http://localhost:8000/api/auth/62b2ff78dec99ecd2d456725

###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username":"denikurnia111000",
    "password":"denikurnia11"
}

###
GET http://localhost:8000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjMyZTJiOWMyZjE0OGY4YjkwMDNmNyIsIm5hbWUiOiJCYW5nIERlZW4iLCJ1c2VybmFtZSI6ImRlbmlrdXJuaWExMTEwMDAiLCJpYXQiOjE2NTU5OTk0MjksImV4cCI6MTY1NTk5OTQzOX0.RpcmXdAo7Mjrb0fxs84QrrFQwuaqA_CV2lzoAYSH2OQ

###
GET http://localhost:8000/api/auth/token

###
DELETE http://localhost:8000/api/auth/logout
